# Generated by Django 6.0 on 2026-02-12 23:07

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('bot_external_id', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('contacto_principal_email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('channel_type', models.CharField(max_length=40)),
                ('metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('CLIENT', 'Cliente'), ('ADMIN', 'Admin'), ('DEV', 'Developer')], default='CLIENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.IntegerField()),
                ('details', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by_user', models.ForeignKey(blank=True, db_column='assigned_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bot', models.ForeignKey(db_column='bot_id', on_delete=django.db.models.deletion.CASCADE, to='core.bot')),
                ('client_account', models.ForeignKey(db_column='client_account_id', on_delete=django.db.models.deletion.CASCADE, to='core.clientaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('started_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bot')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=20)),
                ('sent_by_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('delivery_status', models.CharField(max_length=40)),
                ('error_code', models.CharField(max_length=80)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation')),
                ('sent_by_user', models.ForeignKey(blank=True, db_column='sent_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=80)),
                ('severity', models.CharField(max_length=30)),
                ('error_message', models.TextField()),
                ('stacktrace', models.TextField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.message')),
            ],
        ),
        migrations.CreateModel(
            name='ClientUserMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_en_cliente', models.CharField(max_length=60)),
                ('client_account', models.ForeignKey(db_column='client_account_id', on_delete=django.db.models.deletion.CASCADE, to='core.clientaccount')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client_account', 'user')},
            },
        ),
    ]
