# Generated by Codex on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_role_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="accepted_terms",
            field=models.BooleanField(default=False),
        ),
    ]
