# Generated by Codex on 2026-03-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customuser_accepted_terms_and_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="channel_type",
            field=models.CharField(default="whatsapp", max_length=40),
        ),
        migrations.AddField(
            model_name="bot",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="bot",
            name="external_phone_number_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="bot",
            name="n8n_webhook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="n8n_workflow_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="bot",
            name="provider",
            field=models.CharField(default="n8n", max_length=60),
        ),
        migrations.AddField(
            model_name="conversation",
            name="channel_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="conversation",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="external_thread_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="conversation",
            name="client_account",
            field=models.ForeignKey(blank=True, db_column="client_account_id", null=True, on_delete=django.db.models.deletion.CASCADE, to="core.clientaccount"),
        ),
        migrations.AddField(
            model_name="message",
            name="external_message_id",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="message",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
